"""media_paths many-to-one

Revision ID: 4754265ac29b
Revises: 4389bc0326e9
Create Date: 2026-07-20 02:22:14.857713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4754265ac29b'
down_revision: Union[str, Sequence[str], None] = '4389bc0326e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_paths',
    sa.Column('local_path', sa.Text(), nullable=False),
    sa.Column('sha1', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sha1'], ['media_objects.sha1'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('local_path')
    )
    op.create_index('ix_media_paths_sha1', 'media_paths', ['sha1'], unique=False)
    # Hand-added: carry the old one-path-per-object data over BEFORE the column
    # goes away. This recovers only the last path written per sha1 (the very
    # limitation this table exists to fix) — re-run scripts/seed_catalog.py to
    # register every path that shares a content hash.
    op.execute("""
        INSERT INTO media_paths (local_path, sha1)
        SELECT local_path, sha1 FROM media_objects WHERE local_path IS NOT NULL
        ON CONFLICT (local_path) DO NOTHING
    """)
    op.drop_index(op.f('ix_media_objects_local_path'), table_name='media_objects')
    op.drop_column('media_objects', 'local_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_objects', sa.Column('local_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_media_objects_local_path'), 'media_objects', ['local_path'], unique=False)
    # Hand-added: collapse many paths back to one per object (lossy by nature).
    op.execute("""
        UPDATE media_objects m SET local_path = (
            SELECT p.local_path FROM media_paths p WHERE p.sha1 = m.sha1
            ORDER BY p.local_path LIMIT 1)
    """)
    op.drop_index('ix_media_paths_sha1', table_name='media_paths')
    op.drop_table('media_paths')
    # ### end Alembic commands ###
