"""create catalog tables

Revision ID: 4389bc0326e9
Revises: 
Create Date: 2026-07-20 01:39:26.323294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4389bc0326e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_objects',
    sa.Column('sha1', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('mime', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('oss_key', sa.Text(), nullable=True),
    sa.Column('local_path', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('video', 'image', 'audio', 'episode', 'evidence')", name='ck_media_kind'),
    sa.CheckConstraint("sha1 ~ '^[0-9a-f]{40}$'", name='ck_media_sha1_hex'),
    sa.PrimaryKeyConstraint('sha1'),
    sa.UniqueConstraint('oss_key')
    )
    op.create_index('ix_media_objects_local_path', 'media_objects', ['local_path'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('premise', sa.Text(), nullable=False),
    sa.Column('pack', sa.Text(), nullable=False),
    sa.Column('max_shots', sa.Integer(), nullable=False),
    sa.Column('custom_checks', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('style_descriptor', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'live'"), nullable=False),
    sa.Column('episode_sha1', sa.Text(), nullable=True),
    sa.Column('episode_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('publish_rev', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('raw_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("source IN ('live', 'demo', 'fixtures', 'seed')", name='ck_projects_source'),
    sa.CheckConstraint("status IN ('queued', 'scripting', 'tier0', 'awaiting_review', 'drafting', 'verifying', 'repairing', 'promoting', 'assembling', 'done', 'failed')", name='ck_projects_status'),
    sa.ForeignKeyConstraint(['episode_sha1'], ['media_objects.sha1'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cast_members',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('voice', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'speaker')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('ts', sa.Double(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('tokens_out', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('images', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('video_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('cached_seconds', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('latency_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.CheckConstraint("kind IN ('chat', 'vlm', 'image', 'video_draft', 'video_final', 'video_patch', 'audio')", name='ck_ledger_kind'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ledger_project_ts', 'ledger_entries', ['project_id', 'ts'], unique=False)
    op.create_table('shots',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('assertions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('certified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('still_sha1', sa.Text(), nullable=True),
    sa.Column('still_path', sa.Text(), nullable=True),
    sa.Column('final_sha1', sa.Text(), nullable=True),
    sa.Column('final_path', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'tier0', 'drafting', 'verifying', 'repairing', 'certified', 'failed')", name='ck_shots_status'),
    sa.ForeignKeyConstraint(['final_sha1'], ['media_objects.sha1'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['still_sha1'], ['media_objects.sha1'], ),
    sa.PrimaryKeyConstraint('project_id', 'shot_index')
    )
    op.create_table('assertion_results',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('take_no', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('advisory', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('detail', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('measured', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'pass', 'fail', 'inconclusive')", name='ck_ar_status'),
    sa.CheckConstraint("tier IN ('tier0', 'tier_a', 'tier_b')", name='ck_ar_tier'),
    sa.CheckConstraint("type IN ('duration_between', 'brightness_range', 'flicker_below', 'scene_cuts', 'camera_motion', 'palette_deltae', 'subject_present', 'identity_consistent', 'action_completed', 'title_card_present')", name='ck_ar_type'),
    sa.ForeignKeyConstraint(['project_id', 'shot_index'], ['shots.project_id', 'shots.shot_index'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ar_lookup', 'assertion_results', ['project_id', 'shot_index', 'take_no'], unique=False)
    op.create_index('ix_ar_type_status', 'assertion_results', ['type', 'status'], unique=False)
    op.create_table('takes',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('shot_index', sa.Integer(), nullable=False),
    sa.Column('take_no', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('task_id', sa.Text(), nullable=True),
    sa.Column('video_sha1', sa.Text(), nullable=True),
    sa.Column('video_path', sa.Text(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'generating', 'done', 'failed')", name='ck_takes_status'),
    sa.CheckConstraint("tier IN ('draft', 'final', 'repair', 'patch')", name='ck_takes_tier'),
    sa.ForeignKeyConstraint(['project_id', 'shot_index'], ['shots.project_id', 'shots.shot_index'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_sha1'], ['media_objects.sha1'], ),
    sa.PrimaryKeyConstraint('project_id', 'shot_index', 'take_no')
    )
    # ### end Alembic commands ###

    # Hand-added: autogenerate does not manage views. Inlined (not imported from
    # server/db/models.py) so this revision stays frozen; the models module keeps
    # the same SQL as PROJECT_WALLETS_VIEW for reference. Mirrors
    # Wallet.from_entries (server/metrics.py): a clip counts only when
    # video_seconds > 0, so cache replays stay free. Unit sums only — est_usd is
    # computed in Python from the price tables.
    op.execute("""
        CREATE VIEW project_wallets AS
        SELECT project_id,
               sum(tokens_in)     AS tokens_in,
               sum(tokens_out)    AS tokens_out,
               sum(images)        AS images,
               sum(video_seconds) AS video_seconds,
               count(*) FILTER (WHERE kind = 'video_draft' AND video_seconds > 0) AS draft_clips,
               count(*) FILTER (WHERE kind = 'video_final' AND video_seconds > 0) AS final_clips,
               count(*) FILTER (WHERE kind = 'video_patch' AND video_seconds > 0) AS patch_clips
        FROM ledger_entries
        WHERE project_id IS NOT NULL
        GROUP BY project_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS project_wallets")  # hand-added, see upgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('takes')
    op.drop_index('ix_ar_type_status', table_name='assertion_results')
    op.drop_index('ix_ar_lookup', table_name='assertion_results')
    op.drop_table('assertion_results')
    op.drop_table('shots')
    op.drop_index('ix_ledger_project_ts', table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('cast_members')
    op.drop_table('projects')
    op.drop_index('ix_media_objects_local_path', table_name='media_objects')
    op.drop_table('media_objects')
    # ### end Alembic commands ###
