"""Alembic environment — sync engine, URL from settings.DATABASE_URL.

Env-var-driven URL, dated revision files, migrations autogenerated from the
SQLAlchemy models in server/db/models.py (`alembic revision --autogenerate`).
One deliberate choice: a sync engine — this app is sync psycopg + threads, not
asyncpg, so an async engine would only add ceremony.
"""

from logging.config import fileConfig

from sqlalchemy import create_engine, pool

from alembic import context

from server.db.models import Base

config = context.config

# server/db invokes upgrades programmatically at pool-open time and sets this
# attribute so alembic.ini's [loggers] section can't reconfigure app logging.
if config.config_file_name is not None and not config.attributes.get("skip_logging_setup"):
    fileConfig(config.config_file_name)

target_metadata = Base.metadata


def _database_url() -> str:
    from server.config import settings

    url = config.attributes.get("database_url") or settings.DATABASE_URL
    if not url:
        raise RuntimeError("DATABASE_URL is not set (env or .env) — nothing to migrate")
    # SQLAlchemy's bare postgresql:// scheme defaults to the psycopg2 dialect;
    # this project ships psycopg 3, so pin the dialect explicitly.
    return url.replace("postgresql://", "postgresql+psycopg://", 1)


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of executing (alembic upgrade --sql)."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = create_engine(_database_url(), poolclass=pool.NullPool)
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()
    connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
